version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: postgres_server
    restart: unless-stopped
    ports:
      - 5431:5432

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mlflow -d mlflow"]
      interval: 5s
      timeout: 3s
      retries: 10

    volumes:
      - pg_data:/var/lib/postgresql/data
    networks: [data-net]
    env_file:
      - .env

  mlflow:
    build:
      context: .
      dockerfile: ./mlflow/Dockerfile
    container_name: mlflow_server
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 5000:5000
    env_file:
      - .env

  api:
    build:
      context: ..
      dockerfile: .docker/api/Dockerfile
    container_name: horse-api
    networks: [data-net]
    env_file:
      - .env

volumes:
  pg_data:

networks:
  data-net:
      driver: bridge