version: "3.9"

services:
  database:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5431:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
  minio:

  mlflow:

  app:


volumes:
  pg_data:

networks:
  data-net:
      driver: bridge